package com.neo4flix.movie_service.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.Node;
import org.springframework.data.neo4j.core.schema.Relationship;
import org.springframework.data.neo4j.core.support.UUIDStringGenerator;

import java.time.Instant;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;

// UUID id generated by SDN (UUIDStringGenerator), matches the movie_id_unique constraint in schema.cypher.
@Node("Movie")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(of = "movieId")
@ToString(exclude = "genres")
public class Movie {

    @Id
    @GeneratedValue(UUIDStringGenerator.class)
    private String movieId;

    private String title;

    private String originalTitle;

    private LocalDate releaseDate;

    private Integer durationMinutes;

    private String synopsis;

    private String posterUrl;

    // Denormalized, recalculated by rating-service on every new rating. Read-only here.
    @Builder.Default
    private Double averageRating = 0.0;

    private Instant createdAt;

    @Relationship(type = "IN_GENRE", direction = Relationship.Direction.OUTGOING)
    @Builder.Default
    private Set<Genre> genres = new HashSet<>();

    public void addGenre(Genre genre) {
        this.genres.add(genre);
    }
}
